<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RulesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('rules')->insert([
            // RULE 1: Pre-Hipertensi
            [
                'penyakit_id' => 'P01',
                'gejala_id' => 'G01',
                'solusi_id' => 'S01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P01',
                'gejala_id' => 'G06',
                'solusi_id' => 'S01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P01',
                'gejala_id' => 'G07',
                'solusi_id' => 'S01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P01',
                'gejala_id' => 'G18',
                'solusi_id' => 'S01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P01',
                'gejala_id' => 'G26',
                'solusi_id' => 'S01',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RULE 2: Hipertensi Ringan
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G02',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G05',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G06',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G07',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G08',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G12',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G16',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G21',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G24',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G26',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P02',
                'gejala_id' => 'G27',
                'solusi_id' => 'S02',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RULE 3: Hipertensi Berat
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G03',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G05',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G06',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G07',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G08',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G09',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G10',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G11',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G12',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G13',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G14',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G15',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G17',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G20',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G21',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G22',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G23',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G24',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G25',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G26',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P03',
                'gejala_id' => 'G28',
                'solusi_id' => 'S03',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RULE 4: Hipertensi Maligna/Darurat
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G04',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G05',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G06',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G08',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G10',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G11',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G13',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G14',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G15',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G19',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G20',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G21',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G22',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G23',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G25',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'penyakit_id' => 'P04',
                'gejala_id' => 'G28',
                'solusi_id' => 'S04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

